SOCIAL_AUTH_VK_OAUTH2_KEY = '5517607'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'uzDQPp5HrVFjs0fDfvji'
PAYPAL_TEST = True
PAYPAL_WPP_USER = "vedcrt1004-facilitator_api1.gmail.com"
PAYPAL_WPP_PASSWORD = "GXN3GDCQVW3AFZ5V"
PAYPAL_WPP_SIGNATURE = "ASHE8S-okzitirZP.Ar29HF5GIFEAUqayfZ0W47yvR9h7bJBHTNWcBsa"